### ISSUE TITLE
rfpkg and rpmfusion-packager needs an update for f30

### ISSUE THREAD

**Issue by raveit65** [rpmfusion-infra/rfpkg#15]
Latest fedora-packager obsoletes packagedb-cli, in result you can't install rfpkg and rpmfusion-packager any more.

**Comment by kwizart** [comment]
Seems like it's not only a packaging issue to remove packagedb-cli there is also a need to clean the rfpkg code from using packagecli python module.

Anyone to pick that task ?

**Comment by sergiomb2** [comment]
OK , this will be my priority next weekend , I checked fedpkg works in Py3 since F29 (with same code of F28 btw)

**Comment by leigh123linux** [comment]
> Seems like it's not only a packaging issue to remove packagedb-cli there is also a need to clean the rfpkg code from using packagecli python module.
> 
> Anyone to pick that task ?

Don't we need pkgdb-admin from packagedb-cli?, adapting it for rpmfusion seems easy enough.

https://koji.rpmfusion.org/koji/taskinfo?taskID=280278

**Comment by kwizart** [comment]
> Don't we need pkgdb-admin from packagedb-cli?, adapting it for rpmfusion seems easy enough.

There will be a need to port it to python3 if we want to avoid using a python2 package.

**Comment by ferdnyc** [comment]
> > Don't we need pkgdb-admin from packagedb-cli?, adapting it for rpmfusion seems easy enough.
> 
> There will be a need to port it to python3 if we want to avoid using a python2 package.

That should be the easy part, with `python3-futurize`. The sticking point was its use of the now-obsoleted `fedora_cert`. From that build log it looks like @leigh123linux is one step ahead of me as usual, and has already patched it to replace `fedora_cert` with `rpmfusion_cert`. That was going to be my next move, since I've [already done](https://github.com/rpmfusion-infra/rpmfusion-packager/pull/3) a Python 3 port of `rpmfusion_cert`. (Which is only on hold because `rfpkg` uses it, so the dependencies are kind of circular right now.)

So if we adopt `packagedb-cli` with the `rpmfusion_cert` patch as `rfpkgdb-cli` or whatever, we can convert that to Python 3, and then I **believe** `rfpkg` will finally have all of its dependencies available in Python 3.

**Comment by sergiomb2** [comment]
> Don't we need pkgdb-admin from packagedb-cli?,

Did you or kwizart need it ? or use it ? ( to create packages I guess) , I never use it with success, I always use web interface

**Comment by kwizart** [comment]
> > Don't we need pkgdb-admin from packagedb-cli?,
> 
> Did you or kwizart need it ? or use it ? ( to create packages I guess) , I never use it with success, I always use web interface

leigh is the current pkgdb admin and recently xavierb joined him. You can request to apply in the pkgdb group in fas, but you are also good at others area ;) . 

There is a need for a modified packagedb-cli to deal with the rpmfusion infra (mostly because the way the websso is used enforcing the fedoraproject.org domain). So importing it in our repository for f30 looks relevant.

**Comment by ferdnyc** [comment]
OK, I've created https://github.com/ferdnyc/rfpkgdb-cli forked from Pingou's latest `packagedb-cli.git` at Fedora, with Leigh's `rpmfusion_cert` patches applied, and a package/module rename to `rfpkgdb-cli` and `rfpkgdb2client` throughout. Built and works on my system.

```console
$ /usr/bin/rfpkgdb-cli branches         
   el6                 EL 6                Active
   el7                 EL 7                Active
   f28                 Fedora 28           Active
   f29                 Fedora 29           Active
   el8                 EL 8                Under Development
   master              Fedora devel        Under Development
Total: 6 collections

$ /usr/bin/rfpkgdb-cli list free/shotcut
   shotcut                          A free, open source, cross-platform video editor
Total: 1 packages
```

There's also a `python3` branch, which is mostly working, except I'm getting bit by [this Python 3 bug](https://bugs.python.org/issue9253) which changed the handling of subparsers in argparse, such that `arg.func(arg)` now throws an exception when no subcommand argument is specified.

```console
# #
# # Python 2 still returns help when run with no args
# #
$ python2 ./cli.py        
usage: pkgdb-cli [-h] [--user USERNAME] [--password PASSWORD] [--nocolor]
                 [--verbose] [--debug] [--version] [--insecure]
                 [--pkgdburl PKGDBURL] [--fasurl FASURL] [--bzurl BZURL]
                 [--cgiturl CGITURL] [--kojihuburl KOJIHUBURL]
                 {acl,give,list,orphan,unorphan,request,update,branches,pending,monitoring,koschei}
                 ...
pkgdb-cli: error: too few arguments

# #
# # And it still works
# #
$ python2 ./cli list free/shotcut
   shotcut                          A free, open source, cross-platform video editor
Total: 1 packages

# #
# # But in Python 3 the argument parser can't handle missing subargument
# #
$ python3 ./cli.py
Error: 'Namespace' object has no attribute 'func'
ERROR:root:Generic error catched:
Traceback (most recent call last):
  File "./cli.py", line 1017, in main
    arg.func(arg)
AttributeError: 'Namespace' object has no attribute 'func'

# #
# # Though it still works generally
# #
$ python3 ./cli.py list free/shotcut
b'   shotcut                          A free, open source, cross-platform video editor'
Total: 1 packages
```

(As you can see, I also have some string-encoding issues to fix up.)

**Comment by ferdnyc** [comment]
Fixed. The output will be slightly different between Py2 and Py3 in the no-arguments case, but the functionality is the same:
```console
$ python2 ./cli.py
usage: rfpkgdb-cli [-h] [--user USERNAME] [--password PASSWORD] [--nocolor]
                   [--verbose] [--debug] [--version] [--insecure]
                   [--pkgdburl PKGDBURL] [--fasurl FASURL] [--bzurl BZURL]
                   [--cgiturl CGITURL] [--kojihuburl KOJIHUBURL]
                   {acl,give,list,orphan,unorphan,request,update,branches,pending,monitoring,koschei}
                   ...
rfpkgdb-cli: error: too few arguments

$ python2 ./admin.py
usage: rfpkgdb-admin [-h] [--user USERNAME] [--password PASSWORD] [--verbose]
                     [--debug] [--version] [--insecure] [--pkgdburl PKGDBURL]
                     [--fasurl FASURL] [--bzurl BZURL]
                     {list,update,process,info} ...
rfpkgdb-admin: error: too few arguments

$ python3 ./cli.py                        
usage: rfpkgdb-cli [-h] [--user USERNAME] [--password PASSWORD] [--nocolor]
                   [--verbose] [--debug] [--version] [--insecure]
                   [--pkgdburl PKGDBURL] [--fasurl FASURL] [--bzurl BZURL]
                   [--cgiturl CGITURL] [--kojihuburl KOJIHUBURL]
                   {acl,give,list,orphan,unorphan,request,update,branches,pending,monitoring,koschei}
                   ...
rfpkgdb-cli: error: the following arguments are required: command

$ python3 ./admin.py
usage: rfpkgdb-admin [-h] [--user USERNAME] [--password PASSWORD] [--verbose]
                     [--debug] [--version] [--insecure] [--pkgdburl PKGDBURL]
                     [--fasurl FASURL] [--bzurl BZURL]
                     {list,update,process,info} ...
rfpkgdb-admin: error: the following arguments are required: command

$ python3 ./cli.py list free/shotcut
   shotcut                          A free, open source, cross-platform video editor
Total: 1 packages

# #
# # Of course, I can't test much of rfpkgdb-admin...
# #
$ python3 ./admin.py --verbose list Approved|tail -n10
INFO:rfpkgdb-admin:status  : Approved
      review: https://bugzilla.rpmfusion.org/5047
#315 (Approved) - kwizart requested the new package "nonfree/dynamips" on "f28"
      review: https://bugzilla.rpmfusion.org/5047
#316 (Approved) - kwizart requested the new package "nonfree/dynamips" on "f27"
      review: https://bugzilla.rpmfusion.org/5047
#317 (Approved) - kwizart requested the new package "nonfree/dynamips" on "el7"
      review: https://bugzilla.rpmfusion.org/5047
#318 (Approved) - kwizart requested the new package "nonfree/intel-media-driver" on "master"
      review: https://bugzilla.rpmfusion.org/5045
Total: 250 actions
```

So I believe this is now ready. For command-line use (though testing — especially by @leigh123linux or xavierb, for the admin powers — would be greatly appreciated), and also to replace `pkgdb2client` in `rfpkg` under either Python 2 or 3.

If you want to test, checking out the master branch and running either `admin.py` or `cli.py` with `python2` should work fine.
```console
$ git clone https://github.com/ferdnyc/rfpkgdb-cli.git
$ cd rfpkgdb-cli/rfpkgdb2client
$ python2 ./cli.py list nonfree/nvidia-settings
   nvidia-settings                  NVIDIA driver control panel
   nvidia-settings-390xx            Configure the NVIDIA 390xx series graphics driver
Total: 2 packages
```

To test my `python3` branch _with_ Python 3, easiest would be to grab my rpmfusion-infra/rpmfusion-packager#3 PR changes (AKA the `python3` branch of my fork at https://github.com/ferdnyc/rpmfusion-packager), then build and install the Python 3 `rpmfusion_cert` into `$HOME/.local`:
```console
$ git clone -b python3 https://github.com/ferdnyc/rpmfusion-packager.git
$ cd rpmfusion-packager
$ autoreconf -i
$ ./configure --with-python3 --prefix=$HOME/.local/
$ make; make install
```
The `$HOME/.local` prefix is in the default `$PYTHONPATH`, so after that commands will work from the cloned `rfpkgdb-cli` repo under `python3` as well:
```console
$ cd /path/to/rfpkgdb-cli/rfpkgdb2client
$ git checkout python3
$ python3 ./cli.py list free/vlc
   vlc                              Multi-platform MPEG, DVD, and DivX player
Total: 1 packages
```

**Comment by ferdnyc** [comment]
Scratch builds of `rfpkgdb-cli` (the Python 2 version) for:
**el7** ([task](http://koji.rpmfusion.org/koji/taskinfo?taskID=280990)): [rfpkgdb-cli-2.15.0-1.el7.noarch.rpm](http://koji.rpmfusion.org/kojifiles/work/tasks/990/280990/rfpkgdb-cli-2.15.0-1.el7.noarch.rpm)
**f28** ([task](http://koji.rpmfusion.org/koji/taskinfo?taskID=280998)): [rfpkgdb-cli-2.15.0-1.fc28.noarch.rpm](http://koji.rpmfusion.org/kojifiles/work/tasks/998/280998/rfpkgdb-cli-2.15.0-1.fc28.noarch.rpm)
**f29** ([task](http://koji.rpmfusion.org/koji/taskinfo?taskID=281002)): [rfpkgdb-cli-2.15.0-1.fc29.noarch.rpm](http://koji.rpmfusion.org/kojifiles/work/tasks/1002/281002/rfpkgdb-cli-2.15.0-1.fc29.noarch.rpm)

f30/rawhide would need the Python 3 `rpmfusion_cert`, so that's still pending.

**Comment by sergiomb2** [comment]
Hi, let's clarify two things , rfpkg needs  packagedb-cli just for `rfpkg retire` when we want retire a package rfpkg try mark package as retired in pkgdb , but this feature never worked in RPMFusion , and involve the mention sso issue , so rfpkg could not depend on packagedb-cli , in practice rfpkg never used it .
And rpmfusion_cert is only need to identify the user , rfpkg just use one function of rpmfusion_cert  ...

**Comment by ferdnyc** [comment]
> Hi, let's clarify two things , rfpkg needs packagedb-cli just for `rfpkg retire` when we want retire a package rfpkg try mark package as retired in pkgdb , but this feature never worked in RPMFusion , and involve the mention sso issue , so rfpkg could not depend on packagedb-cli , in practice rfpkg never used it .
> And rpmfusion_cert is only need to identify the user , rfpkg just use one function of rpmfusion_cert ...

That's true. `rfpkgdb` (or actually its `rfpkgdb2client` module) uses a _bit_ more, since it depends on both that same `read_user_cert` method and the `rpmfusion_cert_error` exception class, but it's still a fairly bare-bones dependency relationship.

What were you thinking, just pull the cert-handling code into `rfpkg` and/or `rfpkgdb2client` directly, instead of bothering with a separate package/module?

**Comment by sergiomb2** [comment]
If we got incompatible python versions between rfpkg and packagedb-cli  , I'm think just drop Requirement of packagedb-cli in rfpkg .
And I was just writing and thinking that we have a scenario that we don't need develop all at same time ... 
but if `rfpkgdb` also depend on `read_user_cert` we may have the same scenario again. :)

**Comment by ferdnyc** [comment]
Well, `rfpkgdb-cli` is the easy one, since it's a whole new package — we can build it for Python 2, Python 3, whatever we want. `rpmfusion_cert` does have to match, but... 

One option, actually, would just be to package `rpmfusion_cert` for **both** Python 2 and Python 3, during this transition period. Then we can build `rfpkg`, and/or install `rfpkgdb-cli`, against either Python 2 or Python 3 with no interruption in compatibility/support. And if we were to remove the `rfpkg` dependency on `rfpkgdb2client` (or don't add it, really, since it currently depends on `pkgdb2client` from Fedora), then those two could be built/upgraded independent of each other, as well.

There are command-line tools that are part of the `rpmfusion_cert` package (not that we actually use them for much of anything) — those would have to be linked to just one of the two Python builds. Not that it  makes any difference which one.

**Comment by kwizart** [comment]
Anything holding the update ?
so far it's possible to drop packagedb-cli from rfpkg. But as it's required for pkgdb-admin tasks it can also be converted to python3 (and re-introduced later once done).

I don't care much about having python2/python3 binding for fedora, but we need to keep python2 (only) support for EL7. If it's easier to convert everything to python3 (only) for fedora (and drop the python2 binding) , fine with me.

**Comment by sergiomb2** [comment]
Just ENOTIME

**Comment by kwizart** [comment]
@ferdnyc anything missing to have this at least settle in f30 ?

**Comment by kwizart** [comment]
Can we move ahead with this @fednyc at least for f30 ?
Thx in advance.

**Comment by sergiomb2** [comment]
Hi , I started analyze this, this weekend , now we don't have python2-rpkg in F30 and rfpkg depends on it , so instead in initial comment that we have a broken dep with rfpkgdb-cli , now we need migrate rfpkg to python 3 ... 

rfpkg was a clone of fedpkg but last sync was in version 1.24 and now fedpkg goes on version 1.36 (12 versions)

**Comment by sergiomb2** [comment]
so , seems to me more easy , go with a pure python3 conversion in rfpkg . But another problem is we need keep python2-version alive for epel 7 .
