### ISSUE TITLE
Is rpkg Python 2 package needed for Fedora 30?

### ISSUE THREAD

**Issue by onosek** [rpmfusion-infra/rfpkg#16]
Hi, I am a maintainer of _rpkg_. We would like not to distribute Python 2 package of _rpkg_ (_python2-rpkg_) in upcoming Fedora 30 release. Is your code ready for this? Python 3 package (_python3-rpkg_) will be available of course. Please, let me know if this is OK for you. Thanks.

**Comment by kwizart** [comment]
Thx, there is indeed another PR and issue to track this.

**Comment by sergiomb2** [comment]
> Hi, I am a maintainer of _rpkg_. We would like not to distribute Python 2 package of _rpkg_ (_python2-rpkg_) in upcoming Fedora 30 release. Is your code ready for this? Python 3 package (_python3-rpkg_) will be available of course. Please, let me know if this is OK for you. Thanks.

yes
```
rpm -q --requires rfpkg
(...)
pyrpkg
(...)

dnf repoquery --available --whatprovides pyrpkg
python2-rpkg-0:1.57-6.fc28.noarch
```

**Comment by sergiomb2** [comment]
@onosek ATM it breaks rfpkg on F30 , today I will try follow fedpkg and migrate rfpkg to python3 for F30
(  fedpkg command switched to python3 on Fedora 29 and RHEL > 7 ) ...

**Comment by Vascom** [comment]
Please do it.
We want upgrade to F30 and rfpkg is only block it.

**Comment by sergiomb2** [comment]
Let's open an RFE in rhbz , to re-enable python2-rpkg

**Comment by Vascom** [comment]
May be better rebase rfpkg to python3?

пт, 15 мар. 2019 г., 19:17 Sérgio Basto <notifications@github.com>:

**Comment by sergiomb2** [comment]
See the python3 fedora review , it will take many time , meanwhile we need that things works

**Comment by sergiomb2** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1689365

**Comment by Vascom** [comment]
Can we add it in rpmfusion repo?

пт, 15 мар. 2019 г., 20:53 Sérgio Basto <notifications@github.com>:

**Comment by sergiomb2** [comment]
maybe as a last resource

**Comment by leigh123linux** [comment]
I'm +1 for delaying branching till someone steps up to do the python3 porting for rfpkg package.
I will veto any idea to add python2-rpkg to rpmfusion repo as it's pointless delaying the move to python3.

**Comment by sergiomb2** [comment]
Please do not delay branching  because of this , anyway we already have RPMFusion Fedora 30, what we don't have is RPMFusion rawhide .
Just in case I started a new copr repo [1] with python2-rpkg that will guarantee rfpkg will work , I'm starting test it today on my VM with F30 .

[1]
https://copr.fedorainfracloud.org/coprs/sergiomb/rpmfusion-infra/

**Comment by kwizart** [comment]
I don't think the delay to have this issue fixed is acceptable at all.

The fix is dead simple for rfpkg, just build python3 only for at least fedora30+/el8 and python2 only for other branches. The only issue is to have pkgdb-admin ported to python3 (PR pending). but this can be disabled until done.
If anything related to porting python2/python3 one should look at fedpkg.

I'm not going to do anything on the infra side until this is contributed by someone else from the community.

**Comment by sergiomb2** [comment]
yes, yesterday I looked at fedpkg and seems more simple that I though 

in meantime my copr repo is working [1]  I haven't test it all but looks like is working . 

[1]
https://copr.fedorainfracloud.org/coprs/sergiomb/rpmfusion-infra/

**Comment by qnixsynapse** [comment]
Any progress in this?

**Comment by sergiomb2** [comment]
move to https://github.com/rpmfusion-infra/rfpkg/issues/15
